### ISSUE TITLE
Fix reference to Algebra-Driven Design

### ISSUE THREAD

**Issue by dmsoares** [graninas/functional-declarative-design-methodology#2]
Hi! Thank you for sharing this document :) I hope you don't mind me opening this issue.
I believe there is an error on reference [11] of the bibliography. It should be `[11] S. Maguire, “Algebra-Driven Design" [...]`.

**Comment by graninas** [comment]
@dmsoares Oh, thank you, one and a half years later! I believe this is fixed now. Closing the issue, - no need any action from your side.
